GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA HEALTHCARE.BRONZE TO ROLE ACCOUNTADMIN;

USE SCHEMA HEALTHCARE.BRONZE;

CREATE STORAGE INTEGRATION HEALTHCARE_INTEGRATION
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'S3'
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::561764228129:role/healthcare-snowpipe'
  STORAGE_ALLOWED_LOCATIONS = ('s3://healthcare-data-vitor/raw_data/', 's3://healthcare-error-vitor');

DESC INTEGRATION HEALTHCARE_INTEGRATION;

CREATE OR REPLACE FILE FORMAT MY_CSV_FORMAT
  TYPE = CSV
  FIELD_DELIMITER = ','
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  PARSE_HEADER = TRUE
  NULL_IF = ('NULL', 'null')
  EMPTY_FIELD_AS_NULL = true;

CREATE OR REPLACE STAGE HEALTHCARE_S3_STAGE
  STORAGE_INTEGRATION = HEALTHCARE_INTEGRATION
  URL = 's3://healthcare-data-vitor/raw_data/'
  FILE_FORMAT = MY_CSV_FORMAT;

ls @HEALTHCARE_S3_STAGE;

CREATE SCHEMA HEALTHCARE.SILVER;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA HEALTHCARE.SILVER TO ROLE ACCOUNTADMIN;

CREATE SCHEMA HEALTHCARE.GOLD;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA HEALTHCARE.GOLD TO ROLE ACCOUNTADMIN;

-- Everything passed this is done in DBT (table creation, transformations, logic, etc)
