version: 2

sources:
  - name: healthcare
    description: >
      Raw CSV files ingested dynamically from Snowflake Stage HEALTHCARE_S3_STAGE into the BRONZE schema.
    database: HEALTHCARE
    schema: BRONZE
    tables:
      - name: NH_OWNERSHIP_OCT2024
      - name: NH_QUALITYMSR_MDS_OCT2024
      - name: NH_COVIDVAXAVERAGES_20241027
      - name: NH_COVIDVAXPROVIDER_20241027
      - name: NH_FIRESAFETYCITATIONS_OCT2024
      - name: NH_HEALTHCITATIONS_OCT2024
      - name: NH_SURVEYDATES_OCT2024
      - name: SWING_BED_SNF_DATA_OCT2024
      - name: NH_PROVIDERINFO_OCT2024
      - name: NH_STATEUSAVERAGES_OCT2024
      - name: FY_2024_SNF_VBP_AGGREGATE_PERFORMANCE
      - name: FY_2024_SNF_VBP_FACILITY_PERFORMANCE
      - name: NH_CITATIONDESCRIPTIONS_OCT2024
      - name: SKILLED_NURSING_FACILITY_QUALITY_REPORTING_PROGRAM_NATIONAL_DATA_OCT2024
      - name: NH_DATACOLLECTIONINTERVALS_OCT2024
      - name: NH_HLTHINSPECCUTPOINTSSTATE_OCT2024
      - name: NH_PENALTIES_OCT2024
      - name: SKILLED_NURSING_FACILITY_QUALITY_REPORTING_PROGRAM_PROVIDER_DATA_OCT2024
      - name: NH_SURVEYSUMMARY_OCT2024
      - name: NH_QUALITYMSR_CLAIMS_OCT2024
