{{ config(materialized='view') }}

WITH source_data AS (
    SELECT * FROM {{ source('healthcare', 'NH_PROVIDERINFO_OCT2024') }}
),

renamed AS (
    SELECT
        "CMS Certification Number (CCN)"                   AS cms_certification_number_ccn,
        "Provider Name"                                    AS provider_name,
        "Provider Address"                                 AS provider_address,
        "City/Town"                                        AS city_town,
        "State"                                            AS state,
        "ZIP Code"                                         AS zip_code,
        "Telephone Number"                                 AS telephone_number,
        "Provider SSA County Code"                         AS provider_ssa_county_code,
        "County/Parish"                                    AS county_parish,
        "Ownership Type"                                   AS ownership_type,
        "Number of Certified Beds"                         AS number_of_certified_beds,
        "Average Number of Residents per Day"              AS average_number_of_residents_per_day,
        "Average Number of Residents per Day Footnote"     AS average_number_of_residents_per_day_footnote,
        "Provider Type"                                    AS provider_type,
        "Provider Resides in Hospital"                     AS provider_resides_in_hospital,
        "Legal Business Name"                              AS legal_business_name,
        "Date First Approved to Provide Medicare and Medicaid Services" AS date_first_approved_to_provide_medicare_and_medicaid_services,
        "Affiliated Entity Name"                           AS affiliated_entity_name,
        "Affiliated Entity ID"                             AS affiliated_entity_id,
        "Continuing Care Retirement Community"             AS continuing_care_retirement_community,
        "Special Focus Status"                             AS special_focus_status,
        "Abuse Icon"                                       AS abuse_icon,
        "Most Recent Health Inspection More Than 2 Years Ago" AS most_recent_health_inspection_more_than_2_years_ago,
        "Provider Changed Ownership in Last 12 Months"     AS provider_changed_ownership_in_last_12_months,
        "With a Resident and Family Council"               AS with_a_resident_and_family_council,
        "Automatic Sprinkler Systems in All Required Areas" AS automatic_sprinkler_systems_in_all_required_areas,
        "Overall Rating"                                   AS overall_rating,
        "Overall Rating Footnote"                          AS overall_rating_footnote,
        "Health Inspection Rating"                         AS health_inspection_rating,
        "Health Inspection Rating Footnote"                AS health_inspection_rating_footnote,
        "QM Rating"                                        AS qm_rating,
        "QM Rating Footnote"                               AS qm_rating_footnote,
        "Long-Stay QM Rating"                              AS long_stay_qm_rating,
        "Long-Stay QM Rating Footnote"                     AS long_stay_qm_rating_footnote,
        "Short-Stay QM Rating"                             AS short_stay_qm_rating,
        "Short-Stay QM Rating Footnote"                    AS short_stay_qm_rating_footnote,
        "Staffing Rating"                                  AS staffing_rating,
        "Staffing Rating Footnote"                         AS staffing_rating_footnote,
        "Reported Staffing Footnote"                       AS reported_staffing_footnote,
        "Physical Therapist Staffing Footnote"             AS physical_therapist_staffing_footnote,
        "Reported Nurse Aide Staffing Hours per Resident per Day" AS reported_nurse_aide_staffing_hours_per_resident_per_day,
        "Reported LPN Staffing Hours per Resident per Day" AS reported_lpn_staffing_hours_per_resident_per_day,
        "Reported RN Staffing Hours per Resident per Day"  AS reported_rn_staffing_hours_per_resident_per_day,
        "Reported Licensed Staffing Hours per Resident per Day" AS reported_licensed_staffing_hours_per_resident_per_day,
        "Reported Total Nurse Staffing Hours per Resident per Day" AS reported_total_nurse_staffing_hours_per_resident_per_day,
        "Total number of nurse staff hours per resident per day on the weekend" AS total_number_of_nurse_staff_hours_per_resident_per_day_on_the_weekend,
        "Registered Nurse hours per resident per day on the weekend" AS registered_nurse_hours_per_resident_per_day_on_the_weekend,
        "Reported Physical Therapist Staffing Hours per Resident Per Day" AS reported_physical_therapist_staffing_hours_per_resident_per_day,
        "Total nursing staff turnover"                     AS total_nursing_staff_turnover,
        "Total nursing staff turnover footnote"            AS total_nursing_staff_turnover_footnote,
        "Registered Nurse turnover"                        AS registered_nurse_turnover,
        "Registered Nurse turnover footnote"               AS registered_nurse_turnover_footnote,
        "Number of administrators who have left the nursing home" AS number_of_administrators_who_have_left_the_nursing_home,
        "Administrator turnover footnote"                  AS administrator_turnover_footnote,
        "Nursing Case-Mix Index"                           AS nursing_case_mix_index,
        "Nursing Case-Mix Index Ratio"                     AS nursing_case_mix_index_ratio,
        "Case-Mix Nurse Aide Staffing Hours per Resident per Day" AS case_mix_nurse_aide_staffing_hours_per_resident_per_day,
        "Case-Mix LPN Staffing Hours per Resident per Day" AS case_mix_lpn_staffing_hours_per_resident_per_day,
        "Case-Mix RN Staffing Hours per Resident per Day"  AS case_mix_rn_staffing_hours_per_resident_per_day,
        "Case-Mix Total Nurse Staffing Hours per Resident per Day" AS case_mix_total_nurse_staffing_hours_per_resident_per_day,
        "Case-Mix Weekend Total Nurse Staffing Hours per Resident per Day" AS case_mix_weekend_total_nurse_staffing_hours_per_resident_per_day,
        "Adjusted Nurse Aide Staffing Hours per Resident per Day" AS adjusted_nurse_aide_staffing_hours_per_resident_per_day,
        "Adjusted LPN Staffing Hours per Resident per Day" AS adjusted_lpn_staffing_hours_per_resident_per_day,
        "Adjusted RN Staffing Hours per Resident per Day"  AS adjusted_rn_staffing_hours_per_resident_per_day,
        "Adjusted Total Nurse Staffing Hours per Resident per Day" AS adjusted_total_nurse_staffing_hours_per_resident_per_day,
        "Adjusted Weekend Total Nurse Staffing Hours per Resident per Day" AS adjusted_weekend_total_nurse_staffing_hours_per_resident_per_day,
        "Rating Cycle 1 Standard Survey Health Date"       AS rating_cycle_1_standard_survey_health_date,
        "Rating Cycle 1 Total Number of Health Deficiencies" AS rating_cycle_1_total_number_of_health_deficiencies,
        "Rating Cycle 1 Number of Standard Health Deficiencies" AS rating_cycle_1_number_of_standard_health_deficiencies,
        "Rating Cycle 1 Number of Complaint Health Deficiencies" AS rating_cycle_1_number_of_complaint_health_deficiencies,
        "Rating Cycle 1 Health Deficiency Score"           AS rating_cycle_1_health_deficiency_score,
        "Rating Cycle 1 Number of Health Revisits"         AS rating_cycle_1_number_of_health_revisits,
        "Rating Cycle 1 Health Revisit Score"              AS rating_cycle_1_health_revisit_score,
        "Rating Cycle 1 Total Health Score"                AS rating_cycle_1_total_health_score,
        "Rating Cycle 2 Standard Health Survey Date"       AS rating_cycle_2_standard_health_survey_date,
        "Rating Cycle 2 Total Number of Health Deficiencies" AS rating_cycle_2_total_number_of_health_deficiencies,
        "Rating Cycle 2 Number of Standard Health Deficiencies" AS rating_cycle_2_number_of_standard_health_deficiencies,
        "Rating Cycle 2 Number of Complaint Health Deficiencies" AS rating_cycle_2_number_of_complaint_health_deficiencies,
        "Rating Cycle 2 Health Deficiency Score"           AS rating_cycle_2_health_deficiency_score,
        "Rating Cycle 2 Number of Health Revisits"         AS rating_cycle_2_number_of_health_revisits,
        "Rating Cycle 2 Health Revisit Score"              AS rating_cycle_2_health_revisit_score,
        "Rating Cycle 2 Total Health Score"                AS rating_cycle_2_total_health_score,
        "Rating Cycle 3 Standard Health Survey Date"       AS rating_cycle_3_standard_health_survey_date,
        "Rating Cycle 3 Total Number of Health Deficiencies" AS rating_cycle_3_total_number_of_health_deficiencies,
        "Rating Cycle 3 Number of Standard Health Deficiencies" AS rating_cycle_3_number_of_standard_health_deficiencies,
        "Rating Cycle 3 Number of Complaint Health Deficiencies" AS rating_cycle_3_number_of_complaint_health_deficiencies,
        "Rating Cycle 3 Health Deficiency Score"           AS rating_cycle_3_health_deficiency_score,
        "Rating Cycle 3 Number of Health Revisits"         AS rating_cycle_3_number_of_health_revisits,
        "Rating Cycle 3 Health Revisit Score"              AS rating_cycle_3_health_revisit_score,
        "Rating Cycle 3 Total Health Score"                AS rating_cycle_3_total_health_score,
        "Total Weighted Health Survey Score"               AS total_weighted_health_survey_score,
        "Number of Facility Reported Incidents"            AS number_of_facility_reported_incidents,
        "Number of Substantiated Complaints"               AS number_of_substantiated_complaints,
        "Number of Citations from Infection Control Inspections" AS number_of_citations_from_infection_control_inspections,
        "Number of Fines"                                  AS number_of_fines,
        "Total Amount of Fines in Dollars"                 AS total_amount_of_fines_in_dollars,
        "Number of Payment Denials"                        AS number_of_payment_denials,
        "Total Number of Penalties"                        AS total_number_of_penalties,
        "Location"                                         AS location,
        "Latitude"                                         AS latitude,
        "Longitude"                                        AS longitude,
        "Geocoding Footnote"                               AS geocoding_footnote,
        "Processing Date"                                  AS processing_date
    FROM source_data
)

SELECT * FROM renamed